@startuml authentication_class

class User {
    int id
    string username
    DiscordUser discordUser
    TwitchUser twitchUser
    TwitterUser twitterUser
    getUsername(): string
}

class Authentication {
    int id
    SocialUserInterface authorizedUser
}

interface SocialUserInterface {
    getSocialId(): string
    getSocialUsername(): string
}

User *- SocialUserInterface
Authentication *-- SocialUserInterface

SocialUserInterface <|.. DiscordUser
SocialUserInterface <|.. TwitchUser
SocialUserInterface <|.. TwitterUser

interface Authorizable {
    getAuthorizeUri(): string
    authorize(string code): SocialUserInterface
}

Authorizable <|.. DiscordApi
Authorizable <|.. TwitchApi
Authorizable <|.. TwitterApi

class AuthenticationService {
    Authorizable authorizable
    AuthenticationRepository repository
}

interface AuthenticationRepository

AuthenticationService *- Authorizable
AuthenticationService *-- AuthenticationRepository

@enduml